#!/bin/bash
export DISPLAY=:0

while true; do 
    clear
    figlet Menu
    printf " (a) alarm \n (x) plex \n (g) games \n (s) spotify \n (r) redhshift \n (p) power \n"

    read -n 1 opt1
    case $opt1 in
        a)
            while true; do
                clear
                figlet Alarm
                printf " (5) 05:00 \n (6) 06:00 \n (7) 07:00 \n (8) 08:00 \n (9) 09:00 \n (1) 10:00 \n (q) main menu \n"
                read -n 1 opt2
                case $opt2 in
                    5)
                        sudo ${HOME}/Scripts/WakeupAlarm/suspend_wakeup.sh 5:00 
                        ;;
                    6)
                        sudo ${HOME}/Scripts/WakeupAlarm/suspend_wakeup.sh 6:00 
                        ;;
                    7)
                        sudo ${HOME}/Scripts/WakeupAlarm/suspend_wakeup.sh 7:00 
                        ;;
                    8)
                        sudo ${HOME}/Scripts/WakeupAlarm/suspend_wakeup.sh 8:00 
                        ;;
                    9)
                        sudo ${HOME}/Scripts/WakeupAlarm/suspend_wakeup.sh 9:00 
                        ;;
                    1)
                        sudo ${HOME}/Scripts/WakeupAlarm/suspend_wakeup.sh 10:00
                        ;;
                    q)
                        break
                        ;;
                esac
            done
            ;;
                        
        s)
            while true; do
                clear
                figlet Spotify
                printf " (r) run spotify \n (m) pulsemixer \n (s) spotify-tui \n (n) next song \n (p) play/pause \n (q) main menu \n"
                read -n 1 opt2
                case $opt2 in
                    r)
                        killall spotify; sleep 2; com.spotify.Client &
                        ;;
                    m) 
                        pulsemixer
                        ;;
                    s)
                        spt 
                        ;;
                    n)
                        playerctl next -p "spotify"
                        ;;
                    p)
                        playerctl play-pause -p "spotify"
                        ;;
                    q) 
                        break
                        ;;
                esac
            done
            ;;
        r)
            while true; do
                clear
                figlet Redshift
                printf " Brightness: \n (1) 100 \n (2) 25 \n (5) 50, \n (x) redshift off \n (n) screen off \n (q) main menu \n"
                read -n 1 opt2
                case "$opt2" in
                    1)
                        redshift -P -O 3000 -b 1
                        ;;
                    2) 
                        redshift -P -O 3000 -b 0.25
                        ;;
                    5)
                        redshift -P -O 3000 -b 0.5
                        ;;
                    x)
                        redshift -x
                        ;;
                    n)
                        xset dpms force off
                        ;;
                    q)
                        break
                        ;;
                esac
            done
            ;;
        x)
            while true; do 
                clear 
                figlet Plex
                printf " (o) open plex \n (k) kill plex \n (m) pulsemixer \n (q) quit \n"
                read -n 1 opt2
                case "$opt2" in 
                    o)
                        nohup firefox localhost:32400 &>/dev/null &
                        sleep 2; xdotool key 'F11'
                        ;;
                    k) 
                        killall firefox
                        ;;
                    m)
                        pulsemixer
                        ;;
                    q)
                        break
                        ;;
                esac
            done
            ;;

        g)
            while true; do 
                clear 
                figlet Games
                printf " (g) game menu \n (f) fullscreen \n (r) retroarch \n (m) pulsemixer \n (k) kill \n (q) quit \n"
                read -n 1 opt2 
                case "$opt2" in 
                    g)
                        bash ${HOME}/Scripts/GameMenu/game_menu.sh
                        ;;
                    f)
                        xdotool key 'super+f'
                        ;;
                    r)
                        retroarch
                        ;;
                    m)
                        pulsemixer
                        ;;

                    k) 
                        pgrep dolphin-emu && (killall dolphin-emu; killall dolphin-emu)
                        pgrep retroarch && pkill retroarch
                        pgrep m64py && pkill m64py
                        pgrep citra-qt && pkill -9 citra-qt
                        pgrep mgba-qt && pkill mgba-qt
                        pgrep pcsx2-qt && pkill pcsx2-qt
                        ;;
                    q)
                        break
                        ;;
                esac
            done
            ;;

        p)
            while true; do
                clear
                figlet Power
                printf " (s) suspend \n (1) 10m suspend \n (2) 20m suspend \n (q) main menu \n"
                read -n 1 opt2
                case "$opt2" in
                    1)
                        sleep 10m && systemctl suspend
                        ;;
                    2)
                        sleep 20m && systemctl suspend
                        ;;
                    s)
                        systemctl suspend
                        ;;
                    q)
                        break
                        ;;
                esac
            done
            ;;
        q) 
            exit 0
            ;;
        *)
            ;;
    esac
done
        



