#!/bin/bash
i3-msg rename workspace "i1" to "1"
i3-msg rename workspace "i2" to "2"
i3-msg rename workspace "i3" to "3"
i3-msg rename workspace "i4" to "4"
i3-msg rename workspace "i5" to "5"
i3-msg rename workspace "i6" to "6"
i3-msg rename workspace "i7" to "7"
i3-msg rename workspace "i8" to "8"
i3-msg rename workspace "i9" to "9"
i3-msg rename workspace "i10" to "10"
