#!/bin/bash
i3-msg rename workspace "1" to "i1"
i3-msg rename workspace "2" to "i2"
i3-msg rename workspace "3" to "i3"
i3-msg rename workspace "4" to "i4"
i3-msg rename workspace "5" to "i5"
i3-msg rename workspace "6" to "i6"
i3-msg rename workspace "7" to "i7"
i3-msg rename workspace "8" to "i8"
i3-msg rename workspace "9" to "i9"
i3-msg rename workspace "10" to "i10"
