#!/bin/bash
i3-msg rename workspace "1" to "m1"  
i3-msg rename workspace "2" to "m2"  
i3-msg rename workspace "3" to "m3"  
i3-msg rename workspace "4" to "m4"  
i3-msg rename workspace "5" to "m5"  
i3-msg rename workspace "6" to "m6"  
i3-msg rename workspace "7" to "m7"  
i3-msg rename workspace "8" to "m8"  
i3-msg rename workspace "9" to "m9"  
i3-msg rename workspace "10" to "m10"
