#!/bin/bash
i3-msg rename workspace "1" to "s1"
i3-msg rename workspace "2" to "s2"
i3-msg rename workspace "3" to "s3"
i3-msg rename workspace "4" to "s4"
i3-msg rename workspace "5" to "s5"
i3-msg rename workspace "6" to "s6"
i3-msg rename workspace "7" to "s7"
i3-msg rename workspace "8" to "s8"
i3-msg rename workspace "9" to "s9"
i3-msg rename workspace "10" to "s10"
