require('plugins')
require('config_general')
require('autocommands')
require('user_commands')
require('mappings_general')
require('lsp')
require('cmp_config')
require('plugins/telescope')
require('plugins/git')
require('plugins/navigation')
require('plugins/etc')
require('plugins/writing')
require('plugins/treesitter')
require('plugins/dap')
require('highlight')

